bases:
- ../../base/configmap

configMapGenerator:
- name: config-data-url
  behavior: replace
  files:
  - servers.json
  literals:
  - DATA_URL=https://ccnetlsst01.in2p3.fr:65101/dc2_dr6_object_v2
generatorOptions:
  labels:
    kustomize.generated.resources: qserv.ingest
  disableNameSuffixHash: true
