bases:
- ../../base/configmap

configMapGenerator:
- name: config-data-url
  behavior: replace
  files:
  - servers.json
  literals:
  - DATA_URL=https://ccnetlsst01.in2p3.fr:65101/skysim5000_v1.1.1_parquet/
generatorOptions:
  labels:
    kustomize.generated.resources: qserv.ingest
  disableNameSuffixHash: true
