bases:
- ../../base/configmap

configMapGenerator:
- name: config-ingest
  behavior: replace
  files:
  - ingest.yaml
generatorOptions:
  labels:
    kustomize.generated.resources: qserv.ingest
  disableNameSuffixHash: true
