commonLabels:
  org: lsst
  app: qserv

configMapGenerator:
- name: config-data-url
  files:
  - servers.json
  literals:
  - DATA_URL="http://dataserver/DC2/"
generatorOptions:
  labels:
    kustomize.generated.resources: qserv.ingest
  disableNameSuffixHash: true

