commonLabels:
  org: lsst
  app: qserv

configMapGenerator:
- name: config-data-url
  files:
  - servers.json
  literals:
  - DATA_URL="https://raw.githubusercontent.com/lsst-dm/qserv-ingest/tickets/DM-28680/data/cosmoDC2_v1_1_4_image_testintegration/"
generatorOptions:
  labels:
    kustomize.generated.resources: qserv.ingest
  disableNameSuffixHash: true

