commonLabels:
  org: lsst
  app: qserv

configMapGenerator:
- name: config-data-url
  files:
  - servers.json
  literals:
  - DATA_URL="https://raw.githubusercontent.com/lsst-dm/qserv-ingest/master/tests/data/DC2/"
generatorOptions:
  labels:
    kustomize.generated.resources: qserv.ingest
  disableNameSuffixHash: true

