commonLabels:
  org: lsst
  app: qserv
  tier: ingest

resources:
- init.yaml

secretGenerator:
- name: repl-creds 
  files:
  - qserv

configMapGenerator:
- name: config-data-url
  files:
  - servers.json
  literals:
  - DATA_URL="https://raw.githubusercontent.com/lsst-dm/qserv-ingest/master/data/cosmoDC2_v1_1_4_image_testintegration/"
generatorOptions:
  labels:
    kustomize.generated.resources: qserv.ingest
  disableNameSuffixHash: true

