commonLabels:
  app: qserv
  org: lsst

resources:
- dev.yaml

configMapGenerator:
- files:
  - ingest.yaml
  name: config-ingest
generatorOptions:
  disableNameSuffixHash: true
  labels:
    kustomize.generated.resources: qserv.ingest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: INGEST_IMAGE
  newName: qserv/ingest
  newTag: 2022.6.3-rc1-56-g11ce7c0
